package com.example.ai_kit

data class Language(val name: String, val code: String)

fun getLanguageList(): List<Language> {
    return listOf(
        Language("English", "en"),
        Language("Arabic", "ar"),
        Language("Belarusian", "be"),
        Language("Bulgarian", "bg"),
        Language("Bengali", "bn"),
        Language("Catalan", "ca"),
        Language("Czech", "cs"),
        Language("Welsh", "cy"),
        Language("Danish", "da"),
        Language("German", "de"),
        Language("Greek", "el"),
        Language("Esperanto", "eo"),
        Language("Spanish", "es"),
        Language("Estonian", "et"),
        Language("Persian", "fa"),
        Language("Finnish", "fi"),
        Language("French", "fr"),
        Language("Irish", "ga"),
        Language("Galician", "gl"),
        Language("Gujarati", "gu"),
        Language("Hebrew", "he"),
        Language("Hindi", "hi"),
        Language("Croatian", "hr"),
        Language("Haitian", "ht"),
        Language("Hungarian", "hu"),
        Language("Indonesian", "id"),
        Language("Icelandic", "is"),
        Language("Italian", "it"),
        Language("Japanese", "ja"),
        Language("Georgian", "ka"),
        Language("Kannada", "kn"),
        Language("Korean", "ko"),
        Language("Lithuanian", "lt"),
        Language("Latvian", "lv"),
        Language("Macedonian", "mk"),
        Language("Marathi", "mr"),
        Language("Malay", "ms"),
        Language("Maltese", "mt"),
        Language("Dutch", "nl"),
        Language("Norwegian", "no"),
        Language("Polish", "pl"),
        Language("Portuguese", "pt"),
        Language("Romanian", "ro"),
        Language("Russian", "ru"),
        Language("Slovak", "sk"),
        Language("Slovenian", "sl"),
        Language("Albanian", "sq"),
        Language("Swedish", "sv"),
        Language("Swahili", "sw"),
        Language("Tamil", "ta"),
        Language("Telugu", "te"),
        Language("Thai", "th"),
        Language("Tagalog", "tl"),
        Language("Turkish", "tr"),
        Language("Ukrainian", "uk"),
        Language("Urdu", "ur"),
        Language("Vietnamese", "vi"),
        Language("Chinese", "zh")
    )
}
